export const REGISTER_MANUALLY = 'auth/REGISTER_MANUALLY'
export const LOG_IN_FROM_CREDENTIALS = 'auth/LOG_IN_FROM_CREDENTIALS'

export const SET_LOGGED_IN = 'auth/SET_LOGGED_IN'
export const SET_LOGGED_OUT = 'auth/SET_LOGGED_OUT'
